---
- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    user_name: "Jerome Tabiri"
    user_email: "jtabiri@gmail.com"

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      apt: 
        upgrade: dist 
        force_apt_get: yes

    - name: Install DevOps packages
      apt: 
        name:
          - git
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-setuptools
          - python3-wheel
          - ansible 
          - git
          - awscli
        state: latest

    - name: Setup initial git config
      shell: |
          git config --global user.name "{{ user_name }}"
          git config --global user.email "{{ user_email }}"
  
