---
ansible_python_interpreter: /usr/bin/python3
user_name: "Jerome Tabiri"
user_email: "jtabiri@gmail.com"

mysql_user_name: jerome
mysql_user_password: password

mysql_enabled_on_startup: true
mysql_databases:
  - name: devops_db
    encoding: latin1
    collation: latin1_general_ci

mysql_users:
  - name: jerome
    host: "%"
    password: password
    priv: "devops_db.*:ALL"