---
- hosts: localhost
  become: true
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3
    user_name: "Jerome Tabiri"
    user_email: "jtabiri@gmail.com"

  tasks:
    - name: Add GPG key for docker repository
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add GPG key for terraform repository
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present

    - name: Add key 
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add apt repository for stable terraform
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
        state: present

    - name: Add apt repository for stable version of docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Add apt repository for virtualbox 6.1
      apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian focal contrib
        state: present

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600

    - name: Install DevOps packages
      apt: 
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-setuptools
          - python3-wheel
          - ansible 
          - git
          - awscli
          - virtualbox-6.1
          - terraform
          - vagrant
        state: latest

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli 
        - containerd.io

    - name: Add user to docker group
      user:
        name: "jerome"
        groups: docker
        append: true

    - name: Download docker-compose {{ docker_compose_version }}
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: ~/docker-compose
        mode: '+x'

    - name: Check docker-compose exists
      stat: path=~/docker-compose
      register: docker_compose

    - name: Move docker-compose to /usr/local/bin/docker-compose
      command: mv ~/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists

    - name: Setup initial git config
      shell: |
          git config --global user.name "{{ user_name }}"
          git config --global user.email "{{ user_email }}"
