# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder "data", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.define "web" do |web|
    web.vm.box = "wahab_web"
    web.vm.network "private_network", ip: "192.168.33.10"
    web.provision "shell", inline: <<-SHELL
      sudo apt-get install -y apache2
      SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "wahab_db"
    db.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
  SHELL
end
